import pygeode as pyg
import numpy as np
import pylab as pyl
from pygeode.formats import netcdf as nc

lat = pyg.gausslat(32)
lon = pyg.Lon(np.arange(0, 360, 360/64.))

ln_grid, lt_grid = np.meshgrid(lon.values, lat.values)
T_values = 260. + 40*np.exp(-(lt_grid/45.)**2) + 0.05*lt_grid*np.sin(3*ln_grid*np.pi/180.)
T_c = 260. + 40*np.exp(-(lt_grid/45.)**2)
T_wave = 0.05*lt_grid*np.sin(3*ln_grid*np.pi/180.)

T = pyg.Var((lat, lon), name='Temp', values=T_c + T_wave, atts={'units':'K'})
d = pyg.Dataset([T], atts={'history':'Synthetic Temperature data generated by pygeode'})
nc.save('t_sample.nc', d)
